# Database settings
DB_ENGINE: django.db.backends.postgresql
DB_HOST: 0.0.0.0
DB_PORT: 54322

DB_USER: postgres
DB_PASS: postgres
DB_NAME: postgres

DB_TEST_USER: teams_test
DB_TEST_PASS: teams_test
DB_TEST_NAME: db_teams_test

DB_POSTGRES_USER: postgres
DB_POSTGRES_PASS: manuscript
DB_POSTGRES_NAME: postgres

# Redis settings
REDIS_HOST: 127.0.0.1
REDIS_DATABASE: 0

RABBITMQ_HOST: cougar.rmq.cloudamqp.com
RABBITMQ_PORT: 5672
RABBITMQ_VHOST: gafsbpir
RABBITMQ_USER: gafsbpir
RABBITMQ_PASSWORD: nZ9zXTyLeXqx85E3wS2p_8nKvOFnxqBm
RABBITMQ_EXCHANGE_NAME: manuscript.services # default RabbitMQ exchange name
RABBITMQ_QUEUE: teams_queue
RABBITMQ_USER_CREATE_ROUTING_KEY: user.created
RABBITMQ_USER_KICKED_FROM_TEAM_ROUTING_KEY: user.kicked
RABBITMQ_EVENT_EDIT_ROUTING_KEY: event.edited
RABBITMQ_EVENT_CREATE_ROUTING_KEY: event.created

RABBITMQ_TEST_EXCHANGE_NAME: manuscript.services.test # default RabbitMQ exchange name
RABBITMQ_TEST_QUEUE: teams_queue
