# Database settings
DB_ENGINE: django.db.backends.postgresql
DB_HOST: ms_teams_db
DB_PORT: 5432

DB_USER: postgres
DB_PASS: postgres
DB_NAME: postgres

DB_TEST_USER: teams_test
DB_TEST_PASS: teams_test
DB_TEST_NAME: db_teams_test

DB_POSTGRES_USER: postgres
DB_POSTGRES_PASS: manuscript
DB_POSTGRES_NAME: postgres

# Redis settings
REDIS_HOST: 127.0.0.1
REDIS_DATABASE: 0

RABBITMQ_HOST: cougar.rmq.cloudamqp.com
RABBITMQ_PORT: 5672
RABBITMQ_VHOST: gafsbpir
RABBITMQ_USER: gafsbpir
RABBITMQ_PASSWORD: nZ9zXTyLeXqx85E3wS2p_8nKvOFnxqBm
RABBITMQ_EXCHANGE_NAME: manuscript.services # default RabbitMQ exchange name
RABBITMQ_QUEUE: teams_queue

RABBITMQ_QUEUE_USER_CREATED: teams_queue.user.created
RABBITMQ_QUEUE_EVENT_EDIT: teams_queue.event.edit
RABBITMQ_QUEUE_EVENT_CREATE: teams_queue.event.create

# Test
RABBITMQ_TEST_HOST: localhost
RABBITMQ_TEST_PORT: 5672
RABBITMQ_TEST_VHOST: test
RABBITMQ_TEST_USER: manuscript
RABBITMQ_TEST_PASSWORD: manuscript
RABBITMQ_TEST_EXCHANGE_NAME: manuscript.services.test # default RabbitMQ exchange name
RABBITMQ_TEST_QUEUE: test_teams_queue

RABBITMQ_USER_CREATE_ROUTING_KEY: USER_REGISTERED
RABBITMQ_USER_KICKED_FROM_TEAM_ROUTING_KEY: TEAM_PARTICIPANT_KICKED
RABBITMQ_EVENT_EDIT_ROUTING_KEY: EVENT_UPDATED
RABBITMQ_EVENT_CREATE_ROUTING_KEY: EVENT_CREATED
RABBITMQ_USER_LEFT_FROM_TEAM_ROUTING_KEY: TEAM_PARTICIPANT_LEFT
RABBITMQ_USER_JOIN_REQUEST_ROUTING_KEY: TEAM_PARTICIPANT_REQUEST_CREATE
RABBITMQ_USER_JOIN_REQUEST_UPDATED_ROUTING_KEY: TEAM_PARTICIPANT_REQUEST_UPDATE
