# Database settings
DB_ENGINE: django.db.backends.postgresql
DB_HOST: ms_event_db
DB_PORT: 5432

DB_USER: postgres
DB_PASS: postgres
DB_NAME: postgres

DB_TEST_USER: event_test
DB_TEST_PASS: event_test
DB_TEST_NAME: db_event_test

DB_POSTGRES_USER: postgres
DB_POSTGRES_PASS: manuscript
DB_POSTGRES_NAME: postgres

# Redis settings
REDIS_HOST: 127.0.0.1
REDIS_DATABASE: 0

RABBITMQ_HOST: cougar.rmq.cloudamqp.com
RABBITMQ_PORT: 5672
RABBITMQ_VHOST: gafsbpir
RABBITMQ_USER: gafsbpir
RABBITMQ_PASSWORD: nZ9zXTyLeXqx85E3wS2p_8nKvOFnxqBm
RABBITMQ_EXCHANGE_NAME: manuscript.services
RABBITMQ_QUEUE: event_queue
RABBITMQ_USER_CREATE_ROUTING_KEY: user.created
RABBITMQ_EVENT_EDIT_ROUTING_KEY: event.edited
RABBITMQ_EVENT_CREATE_ROUTING_KEY: event.created

RABBITMQ_TEST_EXCHANGE_NAME: manuscript.services.test # default RabbitMQ exchange name
RABBITMQ_TEST_QUEUE: event_queue
