# Database settings
DB_ENGINE: django.db.backends.postgresql
DB_HOST: localhost
DB_PORT: 5432

DB_USER: event
DB_PASS: event
DB_NAME: db_event

DB_TEST_USER: event_test
DB_TEST_PASS: event_test
DB_TEST_NAME: db_event_test

DB_POSTGRES_USER: postgres
DB_POSTGRES_PASS: manuscript
DB_POSTGRES_NAME: postgres

# Redis settings
REDIS_HOST: 127.0.0.1
REDIS_DATABASE: 0
