RABBITMQ_HOST: cougar.rmq.cloudamqp.com
RABBITMQ_PORT: 5672
RABBITMQ_VHOST: gafsbpir
RABBITMQ_USER: gafsbpir
RABBITMQ_PASSWORD: nZ9zXTyLeXqx85E3wS2p_8nKvOFnxqBm
RABBITMQ_EXCHANGE_NAME: manuscript.services # default RabbitMQ exchange name
RABBITMQ_QUEUE: notifications_queue

RABBITMQ_LOCAL_HOST: rabbitmq
RABBITMQ_LOCAL_PORT: 5672
RABBITMQ_LOCAL_VHOST: test
RABBITMQ_LOCAL_USER: manuscript
RABBITMQ_LOCAL_PASSWORD: manuscript
RABBITMQ_LOCAL_EXCHANGE_NAME: manuscript.services
RABBITMQ_LOCAL_QUEUE: event_queue

RABBITMQ_QUEUE_USER_CREATED: notifications_queue.user.created
RABBITMQ_QUEUE_USER_LEFT_FROM_TEAM: notifications_queue.user.left.from.team
RABBITMQ_QUEUE_USER_JOIN_REQUEST: notifications_queue.user.join.request
RABBITMQ_QUEUE_USER_JOIN_REQUEST_UPDATED: notifications_queue.user.join.request.updated
RABBITMQ_QUEUE_USER_KICKED_FROM_TEAM: notifications_queue.user.kicked.from.team

RABBITMQ_USER_CREATE_ROUTING_KEY: USER_REGISTERED
RABBITMQ_EVENT_EDIT_ROUTING_KEY: EVENT_UPDATED
RABBITMQ_EVENT_CREATE_ROUTING_KEY: EVENT_CREATED
RABBITMQ_USER_LEFT_FROM_TEAM_ROUTING_KEY: TEAM_PARTICIPANT_LEFT
RABBITMQ_USER_JOIN_REQUEST_ROUTING_KEY: TEAM_PARTICIPANT_REQUEST_CREATE
RABBITMQ_USER_JOIN_REQUEST_UPDATED_ROUTING_KEY: TEAM_PARTICIPANT_REQUEST_UPDATE
RABBITMQ_USER_KICKED_FROM_TEAM_ROUTING_KEY: TEAM_PARTICIPANT_KICKED

TELEGRAM_TOKEN: 6275510308:AAEcUIfXxRltZQqx47rq6wRjgZPijqHuHsQ
