# Database settings
DB_ENGINE: django.db.backends.postgresql
DB_HOST: localhost
DB_PORT: 5432

DB_USER: users
DB_PASS: users
DB_NAME: db_users

DB_TEST_USER: users_test
DB_TEST_PASS: users_test
DB_TEST_NAME: db_users_test

DB_POSTGRES_USER: postgres
DB_POSTGRES_PASS: manuscript
DB_POSTGRES_NAME: postgres

# Redis settings
REDIS_HOST: 127.0.0.1
REDIS_DATABASE: 0

RABBITMQ_HOST: localhost # or the hostname where RabbitMQ is running
RABBITMQ_PORT: 5672 # default RabbitMQ port
RABBITMQ_VHOST: # default virtual host
RABBITMQ_USER: manuscript # default RabbitMQ username
RABBITMQ_PASSWORD: manuscript # default RabbitMQ password
RABBITMQ_EXCHANGE_NAME: manuscript.services # default RabbitMQ exchange name
RABBITMQ_QUEUE: users_queue
RABBITMQ_USER_CREATE_ROUTING_KEY: user.created

RABBITMQ_TEST_EXCHANGE_NAME: manuscript.services.test # default RabbitMQ exchange name
RABBITMQ_TEST_QUEUE: user_queue
